version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - docker.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
