import type { Metadata } from 'next';
import { Lexend } from 'next/font/google';
import './globals.css';

import NavHeader from '@/components/NavHeader';
import Container from '../provider/Container';
import { ThemeProvider } from '@/provider/theme-provider';

import { Toaster } from '@/components/ui/sonner';
import ReactQueryProvider from '@/provider/ReactQueryProvider';

const lexend = Lexend({
  variable: '--font-lexend',
  subsets: ['vietnamese'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi">
      <body className={` ${lexend.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Container>
            <ReactQueryProvider>
              <NavHeader />
              {children}
              <Toaster />
            </ReactQueryProvider>
          </Container>
        </ThemeProvider>
      </body>
    </html>
  );
}
