import type { Metadata } from 'next';
import { Lexend } from 'next/font/google';
import './globals.css';

import NavHeader from '@/components/NavHeader';
import { NuqsAdapter } from 'nuqs/adapters/next/app';
import { ThemeProvider } from '@/provider/theme-provider';

import { Toaster } from '@/components/ui/sonner';
import ReactQueryProvider from '@/provider/ReactQueryProvider';

const lexend = Lexend({
  variable: '--font-lexend',
  subsets: ['vietnamese'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi">
      <body className={` ${lexend.variable} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <ReactQueryProvider>
            <NuqsAdapter>
              <NavHeader />
              <div className="pt-[76px]">{children}</div>
              <Toaster />
            </NuqsAdapter>
          </ReactQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
