import { QueryRunner } from 'typeorm';
import { Skill } from '@/api/skill/entities/skill.entity';
import { Domain } from 'domain';

export const seedSkills = async (queryRunner: QueryRunner) => {
  const skillRepository = queryRunner.manager.getRepository(Skill);
  const skills = [
    'JavaScript',
    'TypeScript',
    'HTML',
    'CSS',
    'Node.js',
    'React',
    'Angular',
    'Vue.js',
    'Figma',
    'Next.js',
    'NestJS',
    'Express.js',
    'Java',
    'Spring Boot',
    'Python',
    'Django',
    'Flask',
    'C#',
    '.NET',
    'PHP',
    'Laravel',
    'SQL',
    'PostgreSQL',
    'MySQL',
    'MongoDB',
    'Docker',
    'Kubernetes',
    'AWS',
    'Azure',
    'GCP',
    'Git',
    'CI/CD',
    'Jenkins',
    'Linux',
    'REST API',
    'GraphQL',
    'Redis',
    'Firebase',
    'Agile',
    'Scrum',
    'Machine Learning',
    'Deep Learning',
    'Data Science',
    'Data Analysis',
    'Big Data',
    'Hadoop',
    'Spark',
    'TensorFlow',
    'PyTorch',
    'Computer Vision',
    'Natural Language Processing',
    'Cybersecurity',
    'Penetration Testing',
    'DevOps',
    'Terraform',
    'Ansible',
    'Microservices',
    'System Design',
    'Design Patterns',
    'UML',
    'Software Architecture',
    'Clean Code',
    'Test-Driven Development',
    'Unit Testing',
    'Integration Testing',
    'End-to-End Testing',
    'Selenium',
    'Cypress',
    'Playwright',
    'React Native',
    'Flutter',
    'iOS Development',
    'Android Development',
    'Blockchain',
    'Smart Contract',
    'Solidity',
    'Web3.js',
    'Ethical Hacking',
    'Networking',
    'Shell Scripting',
    'Pandas',
    'NumPy',
    'Matplotlib',
    'Jupyter Notebook',
    'Rust',
    'Go (Golang)',
    'Ruby',
    'Scala',
    'Kotlin',
    'Haskell',
    'R',
    'Assembly',
    'Functional Programming',
    'Object-Oriented Programming',
    'Reactive Programming',
    'Svelte',
    'Bootstrap',
    'Tailwind CSS',
    'Webpack',
    'Vite',
    'jQuery',
    'FastAPI',
    'Koa.js',
    'Hapi.js',
    'ASP.NET Core',
    'GraphQL Subscriptions',
    'GraphQL',
    'SQLite',
    'Cassandra',
    'DynamoDB',
    'ElasticSearch',
    'Apache Kafka',
    'Apache Airflow',
    'Vercel',
    'Netlify',
    'Heroku',
    'Helm',
    'Prometheus',
    'Grafana',
    'GitHub Actions',
    'GitLab CI',
    'Mocha',
    'Chai',
    'Jest',
    'JUnit',
    'TestNG',
    'Xamarin',
    'Capacitor',
    'Ionic',
    'Scikit-learn',
    'OpenCV',
    'Hugging Face Transformers',
    'LangChain',
    'OWASP',
    'SSL/TLS',
    'JWT (JSON Web Token)',
    'OAuth2',
    'Domain-Driven Design (DDD)',
    'Continuous Integration',
    'Continuous Deployment',
    'Refactoring',
    'Code Review',
  ];

  const batch: Skill[] = [];

  for (const name of skills) {
    const existing = await queryRunner.manager.findOneBy(Skill, { name });
    if (!existing && !batch.some((skill) => skill.name === name)) {
      batch.push(skillRepository.create({ name }));
    }
  }

  await skillRepository.save(batch);

  console.log('✅ Seeded skills');
};
