const INTERNAL_ERROR_CODE = 10_000;
const UNAUTHORIZED_CODE = 10_001;
const FORBIDDEN_CODE = 10_002;
const UNPROCESSABLE_ENTITY_CODE = 10_003;
const BAD_REQUEST_CODE = 10_004;
const NOT_FOUND_CODE = 10_005;

const USER_ALREADY_EXISTS_CODE = 10_006;
const WRONG_CREDENTIALS_CODE = 10_007;

const EXCEPTION_CODE = {
  INTERNAL_ERROR_CODE,
  UNAUTHORIZED_CODE,
  FORBIDDEN_CODE,
  UNPROCESSABLE_ENTITY_CODE,
  BAD_REQUEST_CODE,
  NOT_FOUND_CODE,
  USER_ALREADY_EXISTS_CODE,
  WRONG_CREDENTIALS_CODE,
};
export default EXCEPTION_CODE;
