import type { Metadata } from 'next';
import { Figtree } from 'next/font/google';
import './globals.css';

import NavHeader from '@/components/NavHeader';
import Container from '../../provider/Container';
import { ThemeProvider } from '@/provider/theme-provider';

const figTree = Figtree({
  variable: '--font-figtree',
  subsets: ['latin'],
});

export async function generateStaticParams() {
  return [{ lang: 'en' }, { lang: 'vi' }];
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function AppLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: 'en' | 'vi' }>;
}>) {
  return (
    <html lang={(await params).lang}>
      <body className={` ${figTree.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Container>
            <NavHeader />
            {children}
          </Container>
        </ThemeProvider>
      </body>
    </html>
  );
}
