import type { Metadata } from 'next';
import { Lexend } from 'next/font/google';
import './globals.css';

import NavHeader from '@/components/NavHeader';
import Container from '../../provider/Container';
import { ThemeProvider } from '@/provider/theme-provider';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { Toaster } from '@/components/ui/sonner';
import ReactQueryProvider from '@/provider/ReactQueryProvider';

const lexend = Lexend({
  variable: '--font-lexend',
  subsets: ['vietnamese'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function AppLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: 'en' | 'vi' }>;
}>) {
  const { locale } = await params;
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body className={` ${lexend.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NextIntlClientProvider messages={messages}>
            <Container>
              <ReactQueryProvider>
                <NavHeader />
                {children}
                <Toaster />
              </ReactQueryProvider>
            </Container>
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
